[project]
name = "datagouv-api"
version = "1.0.0"
description = "French Gouv Opendata API client"
keywords = ["opendata", "gouv", "data.gouv.fr", "bodacc", "calendrier-scolaire"]
requires-python = ">=3.9"
readme = "README.md"
authors = [
    { name = "CNFilms", email = "technique@cinego.net" }
]
dependencies = [
    "requests>=2.25",
    "python-dateutil>=2.8",
    "text2num>=3.0.1",
]

[build-system]
requires = ["setuptools<82"] # pkg_resources.iter_entry_points() changed in v82 and refrain pycharm debug mode usage
build-backend = "setuptools.build_meta"

[tool.coverage.report]
omit = ["tests/*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["datagouvapi*"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "mypy>=1.8",
    "ruff>=0.3",
    "types-requests>=2.32.4.20260107",
    "types-python-dateutil>=2.9.0.20260124",
    "setuptools<82"
]
